#!/bin/bash

NETCDFLIB="-L/usr/local/netcdf-fortran/4.4.3/gnu4.8.5/lib64/ -lnetcdff"

NETCDFINC="-I/usr/local/netcdf-fortran/4.4.3/gnu4.8.5/include/"

CPP1="-cpp -O3 -ffpe-trap=zero -mcmodel=medium -traditional -DLinux -openmp"

export OMP_NUM_THREADS=24
date
gfortran $CPP1 param.f90 write_iso_vert.f90 spline.f90 ispline.f90 main_code.f90 -o result $NETCDFLIB $NETCDFINC

./result
date
rm result *.mod
